### PR TITLE
Added DataPlane.org feeds

### PR DESCRIPTION
**Pull request by jtkristoff**
Hello,

The Dragon Research Group (DRG) has ceased operation as of spring 2016.  I was the managing director of the group and when I left Team Cymru, it was decided DRG would shutdown.  The SSH feeds combine has configured have not been updating since then.  The DRG web site is expected to be shutdown soon so URL fetches would eventually fail completely.  The good news is that I have started a similar project and have some similar feeds you might find useful.  I've committed some changes mirrored after the DRG feeds, but for DataPlane.org feeds.  I'll let you decide if you'd like to remove the DRG feeds entirely and update your wiki.

### CODE REVIEW

**Comment by alexcpsec** [comment]
@krmaxwell did you get a chance to look at it? 

I sent a CLA to @jtkdpu regardless.

**Comment by krmaxwell** [comment]
Not yet, wanted to ping you because I figured you might have some licensing
concerns before I did :)

**Comment by alexcpsec** [comment]
Yeah, that is out the door already. Thanks for pinging me here. I'll let you know when the CLA is signed.

**Comment by jtkristoff** [comment]
Thanks for your time, but I've decided to close this pull request before a merge.

**Comment by alexcpsec** [comment]
No worries, @jtkdpu . Thanks anyway.

**Pull request closed without merging**
