### PR TITLE
Updated plugins with note fields

### LINKED ISSUE #28: Group enrichments
From @alexcpsec in #21:

> I would separate the enrichments by "groups" (for the lack of a better name) in a config file. And the groups would have a list of the sources that would be harvested by them.
> 
> And we start these groups out as "inbound" and "outbound".
> 
> If too generic (i.e, too much work for now), it is fine. But I think this would give you a lot of flexibility for further research (like a "CnC" group, a "malware download" group, etc, etc).

Currently we separate by inbound/outbound which is fine for initial release, but can be enhanced.

### PR DESCRIPTION
**Pull request by lilze**
Closes #28

### CODE REVIEW

**Comment by krmaxwell** [comment]
Thanks! A couple of things:

- Why is CleanMX pulled?
- Spyeye can get pulled, it's inactive now
- Can you fix the alignment on the lists?

**Comment by alexcpsec** [comment]
Also, needs CLA.

**Comment by alexcpsec** [comment]
CLA is done.

**Comment by alexcpsec** [comment]
@lilze Can you also answer / address these also:
* Why is CleanMX pulled? -- this is not actually broken, please put it back. Maybe timeout issue that we need to address.
* Can you fix the alignment on the lists?

**Comment by krmaxwell** [comment]
Can you re-submit this against the `dev` branch, please? Thanks!

**Pull request closed without merging**
