### PR TITLE
new idea for data transfer / feed metadata

### PR DESCRIPTION
**Pull request by paulpc**
This should work partially with the feeds I have in there. There is still quite a bit of messy code, so, obviously it's not ready for the prime time yet, but it's the accumulation of a few ideas discussed on the slack.com site.

I'll try to comment the code some more when I get some time in the next week or so

### CODE REVIEW

**Comment by technoskald** [comment]
I pulled this into the `paulpc-data` branch and fixed some merge conflicts, but please rebase when you get a chance.

Also: is there any way we can avoid the `from parsers import *`? I realize you specified `__all__` in `__init__.py` but I feel like we should avoid that for the purposes of readability and maintainability.

**Comment by paulpc** [comment]
But that will take away from the cool factor and simplicity of adding
parsers. Currently all it takes is a the python file and an entry in the
config file - no additional code changes in the main files. I'll figure
something out.

**Comment by technoskald** [comment]
I get what you're saying and that's attractive. But it feels very un-[Pythonic](https://www.python.org/dev/peps/pep-0020/) to me. Curious what others think, of course. :)

**Comment by paulpc** [comment]
I  need to go see how mgoffin did it in CRITs - i thought that was pretty elegant

**Comment by alexcpsec** [comment]
This is deprecated by #121. Thanks a lot for giving it a go @paulpc, and we really welcome your suggestions for what else we need there to get it good for v0.2.0

**Pull request closed without merging**
